### ISSUE TITLE
./client -c config1.json

### ISSUE THREAD

**Issue by huglester** [martincyprus/wtc-miner-monitor#3]
Hello,
it would be nice, to pass a config path, or even multiple configs. so when monitoring several GPUS, you can use single client instance, with different parameters.

Thank you

**Comment by martincyprus** [comment]
Hi,

I have added support for this, syntax is just:

./client "path to config file" (use "" if path contains spaces or other weird stuff)
e.g.

`client.exe "c:\program files\wtc\monitor\config1.json"`

if you dont want to build it yourself, it will be in next release.. I have no set timeline for this yet, want to get a few features in before i make next release.

cheers
Martin

**Comment by huglester** [comment]
Thank you
